version: "3.1"
services:
  mc:
    image: nextgenhealthcare/connect
    environment:
      - VMOPTIONS=-Xmx512m
    volumes:
      - ./data/volumes/appdata:/opt/connect/appdata
      - ./data/volumes/custom-extensions:/opt/connect/custom-extensions
    secrets:
      - mirth_properties
      - mcserver_vmoptions
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp

secrets:
  mirth_properties:
    file: ./data/secret.properties
  mcserver_vmoptions:
    file: ./data/secret.vmoptions
